### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jasonshave**

### CODE REVIEW

**Comment by ADefWebserver** [comment]
I can't find any C# examples with the 'official' (still in pre-release) SDK. Am I missing anything? That is the reason I have been using this library,

**Comment by jasonshave** [comment]
The SDK was released yesterday. As a good MSFT citizen it's important for me to promote the official library from my company however I like this implementation as well since it comes with some DI goodness and allows for the community to contribute in a different way. 

Since OpenAI supports a streaming response, I'd like to see if this library can support C# events to get a native callback experience when the platform streams data. Not sure if the official SDK will support this feature either.

Keep using it and contribute if you'd like. I'll maintain it for as long as people find it useful.

**Comment by ADefWebserver** [comment]
Yes, we are on the same page. You added the link to the "official" library so no one will get confused. However, a community library can move faster (ChatGPT could drop any day now and I would not expect an official SDK update for weeks). Also it can add helper methods (I'm thinking about uploading and displaying images with DALL-E when that becomes available).

**Comment by ADefWebserver** [comment]
Also see: https://github.com/lucabriguglia/OpenAI.NET

**Pull request merged**
